function GetObjcet(){var elements=new Array();for(var i=0;i<arguments.length;i++){var element=arguments[i];if(typeof element=='string')element=document.getElementById(element);Method.Element.apply(element);if(arguments.length==1)return element;elements.push(element);}
return elements;}
function GetObjcetA(list){var arr=[];for(var i=0,len=list.length;i<len;i++){arr[i]=list[i];}
return arr;}
var Method={Element:function(){this.hide=function(){this.style.display="none";return this;};this.show=function(){this.style.display="";return this;};this.getValue=function(){if(this.value===undefined)return this.innerHTML;else return this.value;};this.setValue=function(s){if(this.value===undefined)this.setInnerHTML(s);else this.value=s;};this.subTag=function(){return GetObjcetA(this.getElementsByTagName(arguments[0])).each(function(n){GetObjcet(n);});};this.remove=function(){return this.parentNode.removeChild(this);};this.nextElement=function(){var n=this;for(var i=0,n;n=n.nextSibling;i++)
if(n.nodeType==1)return GetObjcet(n);return null;};this.previousElement=function(){var n=this;for(var i=0,n;n=n.previousSibling;i++)
if(n.nodeType==1)return GetObjcet(n);return null;};this.getPosition=function(){var e=this;var t=e.offsetTop;var l=e.offsetLeft;while(e=e.offsetParent){if(GetObjcet(e).getStyle('position')=='absolute'||GetObjcet(e).getStyle('position')=='relative')break;t+=e.offsetTop;l+=e.offsetLeft;}
return{x:l,y:t};};this.getStyle=function(name){if(this.style[name])return this.style[name];else if(this.currentStyle)return this.currentStyle[name];else if(document.defaultView&&document.defaultView.getComputedStyle){name=name.replace(/([A-Z])/g,"-GetObjcet1").toLowerCase();var s=document.defaultView.getComputedStyle(this,"");return s&&s.getPropertyValue(name);}else return null;};this.setInnerHTML=function(s){var ua=navigator.userAgent.toLowerCase();s=s.replace(/<script([^>]+)src\s*=\s*\"([^>\"\']*)\"([^>]*)>\s*<\/script>/gi,'');if(ua.indexOf('msie')>=0&&ua.indexOf('opera')<0){s='<div style="display:none">for IE</div>'+s;s=s.replace(/<script([^>]*)>/gi,'<scriptGetObjcet1 defer>');this.innerHTML='';this.innerHTML=s;this.removeChild(this.firstChild);}else{var el_next=this.nextSibling;var el_parent=this.parentNode;el_parent.removeChild(this);this.innerHTML=s;if(el_next)el_parent.insertBefore(this,el_next);else el_parent.appendChild(this);}};},Array:function(){this.indexOf=function(){for(i=0;i<this.length;i++)
if(this[i]==arguments[0])return i;return-1;};this.each=function(fn){for(var i=0,len=this.length;i<len;i++){fn(this[i],i);}
return this;};},String:function(){this.trim=function(){var _re,_argument=arguments[0]||" ";typeof(_argument)=="string"?(_argument==" "?_re=/(^\s*)|(\s*GetObjcet)/g:_re=new RegExp("(^"+_argument+"*)|("+_argument+"*GetObjcet)","g")):_re=_argument;return this.replace(_re,"");};this.stripTags=function(){return this.replace(/<\/?[^>]+>/gi,'');};this.cint=function(){return this.replace(/\D/g,"")*1;};this.hasSubString=function(s,f){if(!f)f="";return(f+this+f).indexOf(f+s+f)==-1?false:true;};}};Method.Array.apply(Array.prototype);Method.String.apply(String.prototype);var Cookie={get:function(n){var dc="; "+document.cookie+"; ";var coo=dc.indexOf("; "+n+"=");if(coo!=-1){var s=dc.substring(coo+n.length+3,dc.length);return unescape(s.substring(0,s.indexOf("; ")));}else{return null;}},set:function(name,value,expires,path,domain,secure){var expDays=expires*24*60*60*3;var expDate=new Date();expDate.setTime(expDate.getTime()+expDays);var expString=expires?"; expires="+expDate.toGMTString():"";var pathString="; path="+(path||"/");var domain=domain?"; domain="+domain:"";document.cookie=name+"="+escape(value)+expString+domain+pathString+(secure?"; secure":"");},del:function(n){var exp=new Date();exp.setTime(exp.getTime()-1);var cval=this.get(n);if(cval!=null)document.cookie=n+"="+cval+";expires="+exp.toGMTString();}}
function jieqi_ajax(){this.init=function(){this.handler=null;this.method="POST";this.queryStringSeparator="?";this.argumentSeparator="&";this.URLString="";this.encodeURIString=true;this.execute=false;this.requestFile=null;this.vars=new Object();this.responseStatus=new Array(2);this.failed=false;this.response="";this.asynchronous=true;this.onLoading=function(){};this.onLoaded=function(){};this.onInteractive=function(){};this.onComplete=function(){};this.onError=function(){};this.onFail=function(){};try{this.handler=new ActiveXObject("Msxml2.XMLHTTP");}catch(e){try{this.handler=new ActiveXObject("Microsoft.XMLHTTP");}catch(e){this.handler=null;}}
if(!this.handler){if(typeof XMLHttpRequest!="undefined"){this.handler=new XMLHttpRequest();}else{this.failed=true;}}};this.setVar=function(name,value,encoded){this.vars[name]=Array(value,encoded);};this.encVar=function(name,value,returnvars){if(true==returnvars){return Array(encodeURIComponent(name),encodeURIComponent(value));}else{this.vars[encodeURIComponent(name)]=Array(encodeURIComponent(value),true);}};this.processURLString=function(string,encode){regexp=new RegExp(this.argumentSeparator);varArray=string.split(regexp);for(i=0;i<varArray.length;i++){urlVars=varArray[i].split("=");if(true==encode){this.encVar(urlVars[0],urlVars[1],false);}else{this.setVar(urlVars[0],urlVars[1],true);}}};this.createURLString=function(urlstring){if(urlstring){if(this.URLString.length){this.URLString+=this.argumentSeparator+urlstring;}else{this.URLString=urlstring;}}
this.setVar("ajax_request",new Date().getTime(),false);urlstringtemp=new Array();for(key in this.vars){if(false==this.vars[key][1]&&true==this.encodeURIString){encoded=this.encVar(key,this.vars[key][0],true);delete this.vars[key];this.vars[encoded[0]]=Array(encoded[1],true);key=encoded[0];}
urlstringtemp[urlstringtemp.length]=key+"="+this.vars[key][0];}
if(urlstring){this.URLString+=this.argumentSeparator+urlstringtemp.join(this.argumentSeparator);}else{this.URLString+=urlstringtemp.join(this.argumentSeparator);}};this.runResponse=function(){eval(this.response);};this.runAJAX=function(urlstring){if(this.failed){this.onFail();}else{if(this.requestFile.indexOf(this.queryStringSeparator)>0){var spoint=this.requestFile.indexOf(this.queryStringSeparator);this.processURLString(this.requestFile.substr(spoint+this.queryStringSeparator.length),false);this.requestFile=this.requestFile.substr(0,spoint);}
this.createURLString(urlstring);if(this.handler){var self=this;if(this.method=="GET"){totalurlstring=this.requestFile+this.queryStringSeparator+this.URLString;this.handler.open(this.method,totalurlstring,this.asynchronous);}else{this.handler.open(this.method,this.requestFile,this.asynchronous);try{this.handler.setRequestHeader("Content-Type","application/x-www-form-urlencoded");}catch(e){}}
this.handler.onreadystatechange=function(){switch(self.handler.readyState){case 1:self.onLoading();break;case 2:self.onLoaded();break;case 3:self.onInteractive();break;case 4:self.response=self.handler.responseText;self.responseXML=self.handler.responseXML;self.responseStatus[0]=self.handler.status;self.responseStatus[1]=self.handler.statusText;if(self.execute){self.runResponse();}
if(self.responseStatus[0]=="200"){self.onComplete();}else{self.onError();}
self.URLString="";break;}}
this.handler.send(this.method=="GET"?null:this.URLString);}}};this.submitForm=function(form){if(this.requestFile==null)this.requestFile=GetObjcet(form).attributes["action"].value;this.runAJAX(Form.serialize(form));};this.init();}
var Ajax={Request:function(vname,vars){var ajax=new jieqi_ajax();var param={method:"",parameters:"",asynchronous:true,onLoading:function(){},onLoaded:function(){},onInteractive:function(){},onComplete:function(){},onError:function(){},onFail:function(){}};for(var key in vars)param[key]=vars[key];if(param["parameters"]!="")ajax.processURLString(param["parameters"],false);ajax.asynchronous=param["asynchronous"];ajax.onLoading=param["onLoading"];ajax.onLoaded=param["onLoaded"];ajax.onInteractive=param["onInteractive"];ajax.onError=param["onError"];ajax.onFail=param["onFail"];ajax.onComplete=param["onComplete"];if(GetObjcet(vname)!=null&&GetObjcet(vname).tagName.toLowerCase()=="form"){ajax.method=param["method"]==""?"POST":param["method"];ajax.submitForm(vname);}else{ajax.method=param["method"]==""?"GET":param["method"];ajax.requestFile=vname;ajax.runAJAX();}},Update:function(vname,vars){var param={outid:"",tipid:"",onLoading:"",outhide:0,cursor:"wait",parameters:""};for(var key in vars)param[key]=vars[key];var isform=(GetObjcet(vname)!=null&&GetObjcet(vname).tagName.toLowerCase()=="form")?true:false;if(typeof param["onLoading"]=='function'){var doLoading=param["onLoading"];}else{var doLoading=function(){if(param["cursor"]!="")document.body.style.cursor=param["cursor"];if(param["tipid"]!=null&&param["tipid"]!=""){GetObjcet(param["tipid"]).setValue(param["onLoading"]);GetObjcet(param["tipid"]).show();}
if(isform)Form.disable(vname);}}
var doComplete=function(){if(param["cursor"]!="")document.body.style.cursor="auto";if(param["tipid"]!=null&&param["tipid"]!=""){GetObjcet(param["tipid"]).setValue("");GetObjcet(param["tipid"]).hide();}
if(param["outid"]!=""){GetObjcet(param["outid"]).setValue(this.response);GetObjcet(param["outid"]).show();}
if(param["outhide"]!=""){setTimeout(function(){GetObjcet(param["outid"]).hide()},param["outhide"]);}
if(isform)Form.enable(vname);}
var doError=function(){if(param["outid"]!="")GetObjcet(param["outid"]).setValue("ERROR:"+this.responseStatus[1]+"("+this.responseStatus[0]+")");if(isform)Form.enable(vname);}
var doFail=function(){alert("Your browser does not support AJAX!");if(isform)Form.enable(vname);}
Ajax.Request(vname,{onLoading:doLoading,onComplete:doComplete,onError:doError,onFail:doFail,parameters:param["parameters"]});},Tip:function(event,url,timeout){event=event?event:(window.event?window.event:null);timeout=timeout?timeout:3000;var eid=event.srcElement?event.srcElement.id:event.target.id;var tid=eid+"_tip";var ele=GetObjcet(eid);var pos=ele.getPosition();var atip=GetObjcet(tid);if(!atip){atip=document.createElement("div");atip.id=tid;atip.style.display="none";atip.className="ajaxtip";document.body.appendChild(atip);atip.onclick=function(){GetObjcet(tid).hide();};}
atip.style.top=(pos.y+ele.offsetHeight+2)+"px";atip.style.left=pos.x+"px";atip.innerHTML="";atip.style.display="";this.Update(url,{outid:tid,tipid:tid,onLoading:"Loading...",outhide:timeout,cursor:"wait"});}}
function loadJs(url){if(arguments.length>=2&&typeof arguments[1]=='function')funload=arguments[1];if(arguments.length>=3&&typeof arguments[2]=='function')funerror=arguments[2];var ss=document.getElementsByTagName("script");for(i=0;i<ss.length;i++){if(ss[i].src&&ss[i].src.indexOf(url)!=-1){if(typeof funload=="function")funload();return;}}
s=document.createElement("script");s.type="text/javascript";s.defer="defer";s.src=url;document.getElementsByTagName("head")[0].appendChild(s);s.onload=s.onreadystatechange=function(){if(this.readyState&&this.readyState=="loading")return;if(typeof funload=="function")funload();}
s.onerror=function(){this.parentNode.removeChild(this);if(typeof funerror=="function")funerror();}}
function GetObj(objName){if(document.getElementById){return eval('document.getElementById("'+objName+'")');}else if(document.layers){return eval("document.layers['"+objName+"']");}else{return eval('document.all.'+objName);}}
function bookmark(){if(readCookie("bookmark")!="yes"){saveCookie("bookmark","yes",1);window.external.AddFavorite('https://www.shumi.la','书迷楼');}}
function saveCookie(name,value,days){if(days){var date=new Date();date.setTime(date.getTime()+(days*24*60*60*3));var expires="; expires="+date.toGMTString();}else{expires="";}
document.cookie=name+"="+value+expires+"; path=/";}
function readCookie(name){var nameEQ=name+"=";var ca=document.cookie.split(';');for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==' '){c=c.substring(1,c.length);}
if(c.indexOf(nameEQ)==0){return c.substring(nameEQ.length,c.length);}}
return null;}
function vote(id){url="/modules/article/uservote.php?id="+id;Ajax.Request(url,{onComplete:function(){alert(this.response.replace(/<br[^<>]*>/g,'\n'));}});}
function addbook(bid){url="/modules/article/addbookcase.php?bid="+bid;Ajax.Request(url,{onComplete:function(){alert(this.response.replace(/<br[^<>]*>/g,'\n'));}});}
function check_bid_by_cookie(bid){var clickbids=readCookie('clickbids');if(null==clickbids){return false;}
var arr_bid=clickbids.split(',');for(var i=arr_bid.length-1;i>=0;i--){if(parseInt(bid)==parseInt(arr_bid[i])){return true;}}
return false;}
function set_bid_in_cookie(bid){var clickbids=readCookie('clickbids');if(null==clickbids){clickbids=bid;}else{clickbids=clickbids+","+bid;}
saveCookie('clickbids',clickbids,1);}
function addvisit(bid){if(!check_bid_by_cookie(bid)){url="/modules/article/articlevisit.php?id="+bid;Ajax.Request(url);set_bid_in_cookie(bid);}}
function addbookcase(bid,cid){url="/modules/article/addbookcase.php?bid="+bid+"&cid="+cid;Ajax.Request(url,{onComplete:function(){alert(this.response.replace(/<br[^<>]*>/g,'\n'));}});}
var jieqiUserInfo=new Array();jieqiUserInfo['jieqiUserId']=0;jieqiUserInfo['jieqiUserUname']='';jieqiUserInfo['jieqiUserName']='';jieqiUserInfo['jieqiUserGroup']=0;if(document.cookie.indexOf('jieqiUserInfo')>=0){var cookieInfo=get_cookie_value('jieqiUserInfo');start=0;offset=cookieInfo.indexOf(',',start);while(offset>0){tmpval=cookieInfo.substring(start,offset);tmpidx=tmpval.indexOf('=');if(tmpidx>0){tmpname=tmpval.substring(0,tmpidx);tmpval=tmpval.substring(tmpidx+1,tmpval.length);jieqiUserInfo[tmpname]=tmpval}
start=offset+1;if(offset<cookieInfo.length){offset=cookieInfo.indexOf(',',start);if(offset==-1)offset=cookieInfo.length}else{offset=-1}}}
function get_cookie_value(Name){var search=Name+"=";var returnvalue="";if(document.cookie.length>0){offset=document.cookie.indexOf(search);if(offset!=-1){offset+=search.length;end=document.cookie.indexOf(";",offset);if(end==-1)end=document.cookie.length;returnvalue=unescape(document.cookie.substring(offset,end))}}
return returnvalue}
function login(){if(jieqiUserInfo['jieqiUserId']>0){document.writeln(" <div class=\"topajax userinfo\">");document.writeln("<a href=\"\/userdetail.php\" class=\"username\" title=\"个人资料\">"+unescape(jieqiUserInfo['jieqiUserName_un'])+"<\/a>")
document.writeln("┊<a href=\"\/modules\/article\/bookcase.php\">我的书架<\/a>")
document.writeln("┊<a href=\"\/logout.php\" class=\"logout\">退出<\/a>")
document.writeln("</div>");}else{document.writeln(" <div class=\"topajax\">");document.writeln("<a class=\"t_a\" href=\"/register.php\">免费注册</a>");document.writeln("            <a class=\"t_a\" href=\"/login.php\">登录</a>");document.writeln("</div>");}}
function SearchBox(){document.writeln("<div class='search'>");document.writeln("            <form target='_blank' method=get action='/modules/article/search.php'>");document.writeln("                <input id=\"bdcsMain\" class=\"searchkey\" placeholder=\"输入少字也别输入错字\" type=text name=searchkey>");document.writeln("                <input class=\"btn\" value=\"搜索\" type=\"submit\" name=\"submit\"></form>");document.writeln("        </div>");}
function foot(){document.writeln("所有小说和章节均由网友上传，转载只为宣传本书让更多读者欣赏。<br>");document.writeln("Copyright &copy; "+new Date().getFullYear()+location.host.replace("www."," ").toUpperCase());}
function readtip(){document.writeln("<p class=\"read-tips\">小技巧：按 Ctrl+D 快速保存当前章节页面至浏览器收藏夹；按 回车[Enter]键 返回章节目录，按 &larr;键 回到上一章，按 &rarr;键 进入下一章。</p>");}
function keyevent(){var index_page=$("#link-index").attr("href");var prev_page=$("#link-preview").attr("href");var next_page=$("#link-next").attr("href");function jumpPage(){var event=document.all?window.event:arguments[0];if(event.keyCode==37)document.location=prev_page;if(event.keyCode==39)document.location=next_page;if(event.keyCode==13)document.location=index_page;}
document.onkeydown=jumpPage;}
function Go(url){function is_mobile(){var regex_match=/(nokia|iphone|android|motorola|^mot-|softbank|foma|docomo|kddi|up.browser|up.link|htc|dopod|blazer|netfront|helio|hosin|huawei|novarra|CoolPad|webos|techfaith|palmsource|blackberry|alcatel|amoi|ktouch|nexian|samsung|^sam-|s[cg]h|^lge|ericsson|philips|sagem|wellcom|bunjalloo|maui|symbian|smartphone|midp|wap|phone|windows ce|iemobile|^spice|^bird|^zte-|longcos|pantech|gionee|^sie-|portalmmm|jigs browser|hiptop|^benq|haier|^lct|operas*mobi|opera*mini|320x320|240x320|176x220)/i;return navigator.userAgent==null||regex_match.exec(navigator.userAgent)!=null;}
if(is_mobile()){window.top.location.href=url;}}
function bd_push(){var bp=document.createElement('script');var curProtocol=window.location.protocol.split(':')[0];if(curProtocol==='https'){bp.src='https://zz.bdstatic.com/linksubmit/push.js';}
else{bp.src='http://push.zhanzhang.baidu.com/push.js';}
var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(bp,s);}